# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

censor_both_c <- function(x, min, max) {
    .Call('_jpw_censor_both_c', PACKAGE = 'jpw', x, min, max)
}

censor_left_c <- function(x, min) {
    .Call('_jpw_censor_left_c', PACKAGE = 'jpw', x, min)
}

censor_right_c <- function(x, max) {
    .Call('_jpw_censor_right_c', PACKAGE = 'jpw', x, max)
}

